name: freeshow
version: 1.3.8
title: FreeShow
summary: FreeShow
description: Show song lyrics and more for free!
platforms:
  amd64:
    build-on: amd64
    build-for: amd64
base: core24
grade: stable
confinement: strict
plugs:
  gnome-46-2404:
    interface: content
    target: $SNAP/gnome-platform
    default-provider: gnome-46-2404
  gtk-3-themes:
    interface: content
    target: $SNAP/data-dir/themes
    default-provider: gtk-common-themes
  icon-themes:
    interface: content
    target: $SNAP/data-dir/icons
    default-provider: gtk-common-themes
  sound-themes:
    interface: content
    target: $SNAP/data-dir/sounds
    default-provider: gtk-common-themes
layout:
  /usr/share/alsa:
    bind: $SNAP/usr/share/alsa
parts:
  freeshow:
    source: https://github.com/ChurchApps/FreeShow.git
    plugin: dump
    stage-packages:
      - libasound2t64
    override-pull: |
      git clone https://github.com/ChurchApps/FreeShow.git
      VERSION=$(craftctl get version | cut -d- -f1)
      git checkout "v${VERSION}"
    override-build: |
      npm install
      npm run build
      npm run pack
      cp -R dist/linux-unpacked $SNAPCRAFT_PRIME
    override-prime: |
      craftctl default
      cp $SNAPCRAFT_PROJECT_DIR/snap/local/*.sh $SNAPCRAFT_PRIME

apps:
  freeshow:
    command: command.sh
    extensions: [gnome]
    plugs:
      - alsa
      - desktop
      - desktop-legacy
      - home
      - x11
      - wayland
      - unity7
      - browser-support
      - network
      - gsettings
      - audio-playback
      - pulseaudio
      - opengl
      - removable-media
    environment:
      PATH: $SNAP/usr/sbin:$SNAP/usr/bin:$SNAP/sbin:$SNAP/bin:$PATH
      SNAP_DESKTOP_RUNTIME: $SNAP/gnome-platform
      LD_LIBRARY_PATH: $SNAP_LIBRARY_PATH:$SNAP/lib:$SNAP/usr/lib:$SNAP/lib/x86_64-linux-gnu:$SNAP/usr/lib/x86_64-linux-gnu:$LD_LIBRARY_PATH:$SNAP/lib:$SNAP/usr/lib:$SNAP/lib/x86_64-linux-gnu:$SNAP/usr/lib/x86_64-linux-gnu
